name: CI

# Trigger the workflow on push to master / main, or on pull request
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: ${{ matrix.gap-version }} on ${{ matrix.os }} with ${{ matrix.configflags }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        gap-version:
          - v4.10
          - v4.11.1
          - stable-4.12
          - v4.13.0-alpha2
          - 4.15.0-beta1
          - 4
          - latest
          - default
          - v4.16dev
        configflags: ['', '--with-gmp=builtin']
        exclude:
          - os: windows-latest
            configflags: '--with-gmp=builtin'
          - os: macos-latest
            gap-version: stable-4.12
          - os: macos-latest
            gap-version: v4.10
          - os: macos-latest
            gap-version: v4.11.1
            configflags: '--with-gmp=builtin'

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Setup Cygwin"
        if: ${{ matrix.os == 'windows-latest' }}
        uses: gap-actions/setup-cygwin@v2

      - name: "Setup GAP"
        uses: ./
        with:
          gap-version: ${{ matrix.gap-version }}
          configflags: ${{ matrix.configflags }}

      - name: "Check if GAP can run"
        shell: bash
        run: |
          gap -A <<GAPINPUT
            quit;
          GAPINPUT
          $GAP -A <<GAPINPUT
            quit;
          GAPINPUT
          $GAPROOT/gap -A <<GAPINPUT
            quit;
          GAPINPUT
